Adde code for local strategy
js-tasks-ru/nodejs-20210126_maximfariga pull request #10
Opened 2021-03-01 12:28 UTC by Pots1988

2021-03-01 12:28 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-03-03 10:08 UTC, tadjik1 commented on 08-authentication/01-local/libs/strategies/local.js
> +      const user = await User.findOne({email});
тут надо обязательно добавить обработку ошибок - try/catch. дело в том, что эта функция принимает коллбек, и таким образом ошибки, которые здесь могут возникнуть не будут перехвачены внешними middleware.

2021-03-03 10:09 UTC, tadjik1 requested changes
@Pots1988 всё сделано очень хорошо! небольшой совсем нюанс по обработке ошибок - нужно добавить try/catch ровно также ,как вы сделали в authenticate

2021-03-05 12:47 UTC, tadjik1 approved these changes
👍

2021-03-05 12:49 UTC, merged